
# ... Service YAML definition

apiVersion: v1
kind: Service
metadata:
  name: movie-rating-service
spec:
  selector:
    app: movie-rating-service
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer